// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// In-memory fallback: ba'zi Telegram WebView muhitlarida (masalan Telegram
// Desktop/Web ichidagi sandboxed iframe) localStorage o'qish/yozish
// bloklangan bo'ladi. Bunday holatda Supabase mijoz kutubxonasi sessiyani
// saqlay olmaydi va auth "muvaffaqiyatli" bo'lsa ham keyinchalik yo'qoladi.
// Shu sababli localStorage mavjudligini avval tekshiramiz va bo'lmasa
// xotiradagi (sahifa yangilanguncha yashaydigan) storage'ga tushamiz.
function isLocalStorageUsable(): boolean {
  if (typeof window === 'undefined') return false;
  try {
    const testKey = '__supabase_storage_test__';
    window.localStorage.setItem(testKey, '1');
    window.localStorage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
}

class MemoryStorage {
  private store = new Map<string, string>();
  getItem(key: string) {
    return this.store.has(key) ? this.store.get(key)! : null;
  }
  setItem(key: string, value: string) {
    this.store.set(key, value);
  }
  removeItem(key: string) {
    this.store.delete(key);
  }
}

// Modul darajasida bitta nusxa — shuning uchun sahifa ichida (SPA
// navigatsiyalarda) sessiya saqlanib qoladi, faqat to'liq reload bo'lsa
// yo'qoladi (bu Telegram Mini App uchun muhim emas, chunki initData orqali
// har safar avtomatik qayta login bo'ladi).
const memoryStorageSingleton = new MemoryStorage();

function createSupabaseClient() {
  // Browser-only client configuration is injected by Vite for public values.
  // Cloudflare Worker server code must use runtime env via src/lib/worker-runtime.ts.
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const usableLocalStorage = isLocalStorageUsable();
  if (!usableLocalStorage && typeof window !== 'undefined') {
    console.warn(
      '[Supabase] localStorage is not usable in this environment (e.g. sandboxed ' +
        'Telegram WebView). Falling back to in-memory session storage; the ' +
        'session will not survive a full page reload.',
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage:
        typeof window !== 'undefined'
          ? usableLocalStorage
            ? localStorage
            : memoryStorageSingleton
          : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});